### ISSUE TITLE
UserEntityMapper.xml有个sql写错了

### ISSUE THREAD

**Issue by gao-classmate** [ZHENFENG13/My-Column#1]
<select id="selectByLoginName" resultType="com.my.column.entity.UserEntity">
    select
    <include refid="Base_Column_List" />
    from tb_user
    **where login_name = #{userId,jdbcType=BIGINT} limit 1**
  </select>

这个sql最后的where条件写错了
应该是
 where login_name = #{loginName,jdbcType=VARCHAR} limit 1

**Comment by ZHENFENG13** [comment]
好的 我看下

**Comment by ZHENFENG13** [comment]
你是不是看错了？刚刚我确认了一下代码，没你说的这个

**Comment by gao-classmate** [comment]
<select id="selectByLoginName" resultType="com.my.column.entity.UserEntity">
    select
    <include refid="Base_Column_List" />
    from tb_user
    where login_name = #{userId,jdbcType=BIGINT} limit 1
  </select>
就是这个参数啊  老哥你这个方法不是根据登录名查找对象嘛  你看后面的where参数写的是userId

**Comment by ZHENFENG13** [comment]
我等下改一下
